project:
  type: "website"
  title: "Research Software Engineering Summer School"

editor:
  render-on-save: true

website:
  title: "Research Software Engineering Summer School"
  page-navigation: true
  reader-mode: true
  open-graph: true
  search:
    location: navbar
    type: textbox
  sidebar:
    collapse-level: 2
    style: docked
    contents:
      - href: index.qmd
        text: "ğŸ  Home"
      - href: installation/julia.qmd
        text: "Installation"
      - href: schedule.qmd
        text: "ğŸ““ Schedule"
      - href: projectwork.qmd
        text: "ğŸ›  Projects"
      - href: social.qmd
        text: ":fire: Social"
      - section: "Cheatsheets"
        contents:
          - href: cheatsheets/julia.qmd
            text: Julia 
          - href: cheatsheets/git.qmd
            text: Git
          - href: cheatsheets/githubactions.qmd
            text: GitHub actions
      - section: "Slides / Handouts"
        contents:
          - section: "Monday"
            contents:
              - href: material/1_mon/rse/rse_basics_slides.qmd
                text: "ğŸ“Š 1 - RSE"
              - href: "material/1_mon/why_julia/page.qmd"
                text: "ğŸ“Š 2 - Why Julia"
              - href: "material/1_mon/firststeps/firststeps_handout.qmd"
                text: "ğŸ“ 3 - First Steps: Handout"
              - href: "material/1_mon/firststeps/tasks.qmd"
                text: "ğŸ›  3 - First Steps: Exercises"
              - href: "material/1_mon/envs/envs_handout.qmd"
                text: "ğŸ“ 4 - Envs & Pkgs : Handout"
              - href: "material/1_mon/envs/tasks.qmd"
                text: "ğŸ›  4 - Envs & Pkgs: Exercises"
          - section: "Tuesday"
            contents: 
              - href: material/2_tue/git/slides.md
                text: "ğŸ“ 1 - Advanced Git and Contributing"
              - href: "material/2_tue/git/tasks.qmd"
                text: "ğŸ›  1 - Git: Exercises"
              - href: "material/2_tue/testing/slides.md"
                text: "ğŸ“ 2 - Testing"
              - href: "material/2_tue/ci/slides.md"
                text: "ğŸ“ 3 - Continuous Integration"
              - href: material/2_tue/codereview/slides.qmd
                text: "ğŸ“ 4 - Code Review"
          - section: "Wednesday"
            contents:
              - href: material/3_wed/docs/handout.qmd
                text: "ğŸ“ 1 - Docs: Handout"
              - href: material/3_wed/docs/tasks.qmd"
                text: "ğŸ›  1 - Docs: Exercises"
              - href: material/3_wed/vis/handout.qmd
                text: "ğŸ“ 2 - Visualizations: Handout"
              - href: material/3_wed/vis/tasks.qmd"
                text: "ğŸ›  2 - Visualizations: Exercises"
              - href: material/3_wed/linalg/slides.qmd
                text: "ğŸ“ 3 - LinearAlgebra"
              - href: material/3_wed/regression/MultipleRegressionBasics.qmd
                text: "ğŸ“ 4 - Multiple Regression"
          
          - section: "Thursday"
            contents:
              - href: material/4_thu/sim/slides.qmd
                text: "ğŸ“ 1 - Simulation"
              - href: material/4_thu/stats/missing.jl
                text: "ğŸ“ 2 - Bootstrapping"
              - href: material/4_thu/parallel/slides.qmd
                text: "ğŸ“ 3 - Parallelization"
          - section: "Friday"
            contents:
              - href: material/5_fri/highlightsOptim/missing.qmd
                text: "ğŸ“ 1 - Highlights + Optimization"
          
  navbar:
    background: primary
  page-footer:
    background: light
    left: "CC-By Ehinger, Oesting, Uekerman, DeBruine, Ranocha, Szufel" 
resources:
  - CNAME

keep-ipynb: true
format:
  html:
    email-obfuscation: javascript
    link-external-newwindow: true
    link-external-icon: true

    theme:
      light: 
        - journal
        - styles.scss # I use this just to change the default colour

    toc: true
    from: markdown+emoji
    toc-expand: 3
    grid:
      body-width: 1000px
      sidebar-width: 400px
    code-annotations: hover
    margin-header: |
      ![](https://www.simtech.uni-stuttgart.de/img/events/Summer-School/Zeichenflaeche-3-Kopie-42x.png?__scale=w:150,h:150)
