project:
  type: "website"
  title: "Research Software Engineering Summer School"

editor:
  render-on-save: true

website:
  title: "Research Software Engineering Summer School"
  page-navigation: true
  reader-mode: true
  open-graph: true
  search:
    location: navbar
    type: textbox
  sidebar:
    collapse-level: 2
    style: docked
    contents:
      - href: index.qmd
        text: "ğŸ  Home"
      - href: installation.qmd
        text: "Installation"
      - href: schedule.qmd
        text: "ğŸ““ Schedule"
      - href: social.qmd
        text: ":fire: Social"
      - section: "Cheatsheets"
        contents:
          - href: cheatsheets/julia.qmd
            text: Julia 
          - href: cheatsheets/git.qmd
            text: Git
          - href: cheatsheets/githubactions.qmd
            text: GitHub actions
      - section: "Slides / Handouts"
        contents:
          - section: "Monday"
            contents:
              - href: material/1_mon/rse/rse_basics_slides.qmd
                text: "ğŸ“Š 1 - RSE"
              - href: "missing.md"
                text: "ğŸ“ 2 - Why Julia"
              - href: "material/1_mon/firststeps/firststeps_handout.qmd"
                text: "ğŸ“ 3 - First Steps"
              - href: "material/1_mon/envs/envs_handout.qmd"
                text: "ğŸ“ 4 - Environments & Packages"
          - section: "Tuesday"
            contents: 
              - href: material/2_tue/git/intro_slides.md
                text: "ğŸ“ 1 - GIT"    
              - href: "material/2_tue/unittest/missing.qmd"
                text: "ğŸ“ 2 - Unit Testing"
              - href: "material/3_tue/CI/missing.qmd"
                text: "ğŸ“ 3 - Continuous Integration"
              - href: "material/4_tue/codereview/missing.qmd"
                text: "ğŸ“ 4 - Code Review"
          - section: "Wednesday"
            contents:
              - href: material/3_wed/docs/handout.qmd
                text: "ğŸ“ 1 - Docs"
              - href: material/3_wed/vis/slides.jl
                text: "ğŸ“ 2 - Visualizations"
              - href: material/3_wed/linearalgebra/missing.qmd
                text: "ğŸ“ 3 - LinearAlgebra"
              - href: material/3_wed/regression/missing.jl
                text: "ğŸ“ 4 - Multiple Regression"
          
          - section: "Thursday"
            contents:
              - href: material/4_thu/sim/missing.qmd
                text: "ğŸ“ 1 - Simulation"
              - href: material/4_thu/stats/missing.jl
                text: "ğŸ“ 2 - Stats"
              - href: material/4_thu/parallel/missing.qmd
                text: "ğŸ“ 3 - Parallelization"
          - section: "Friday"
            contents:
              - href: material/5_fri/highlightsOptim/missing.qmd
                text: "ğŸ“ 1 - Highlights + Optimization"
          
  navbar:
    background: primary
  page-footer:
    background: light
    left: "CC-By Benedikt Ehinger" 
resources:
  - CNAME


format:
  html:
    email-obfuscation: javascript
    link-external-newwindow: true
    link-external-icon: true

    theme:
      light: 
        - journal
        - styles.scss # I use this just to change the default colour

    toc: true
    from: markdown+emoji
    toc-expand: 3
    grid:
      body-width: 1000px
    code-annotations: hover