project:
  type: "website"
  title: "Research Software Engineering Summer School"

editor:
  render-on-save: true

website:
  title: "Research Software Engineering Summer School"
  page-navigation: true
  reader-mode: true
  open-graph: true
  search:
    location: navbar
    type: textbox
  sidebar:
    collapse-level: 3
    style: docked
    contents:
      - href: index.qmd
        text: "ğŸ  Home"
      - href: schedule.qmd
        text: "ğŸ““ Schedule"
      - href: teaching.qmd
        text: "ğŸ“Ÿ Teachers"
      - section: "Slides / Handouts"
        contents:
          - section: "Monday"
            contents:
              - href: material/1_mon/rse/rse_basics_slides.qmd
                text: "ğŸ“Š 1 - RSE"
              - href: "missing.md"
                text: "2 - Why Julia"
              - href: "material/1_mon/firststeps/firststeps_handout.qmd"
                text: "ğŸ“ 3 - First Steps"
              - href: "material/1_mon/envs/envs_handout.qmd"
                text: "ğŸ“ 4 - Environments & Packages"
  navbar:
    background: primary
  page-footer:
    background: light
    left: "CC-By Benedikt Ehinger" 
resources:
  - CNAME


format:
  html:
    email-obfuscation: javascript
    link-external-newwindow: true
    link-external-icon: true

    theme:
      light: 
        - journal
        - styles.scss # I use this just to change the default colour

    toc: true
    from: markdown+emoji
    toc-expand: 3
    grid:
      body-width: 1000px
