[deps]
AlgebraOfGraphics = "cbdf2221-f076-402e-a563-3d30da359d67"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
PalmerPenguins = "8b842266-38fa-440a-9b57-31493939ab85"
